server:
  port: 8080
  servlet:
    context-path: /sharding
spring:
  main:
    # 多数据源必须配置这个。允许一个实体类配置使用多张表，覆盖.
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: level-table